; Tank: armour, damage resistance and no flinch on Med-Kit armour.
[settings]
name = Tank

[profile: Med-Kit]
conflicts = stack
Extra Padding                      = on
Fortified                          = on
Ballistic Padding                  = on
Concussive Padding, Reinforced     = on
Blunt-Force Mitigation             = on
Kinetic Displacement Mitigation    = on
Unflinching                        = on
Democracy Protects                 = on
Supplemental Adrenaline            = on
