; Survivor: more stims, death save, elemental resistance on Med-Kit armour.
[settings]
name = Survivor

[profile: Med-Kit]
conflicts = strongest
Democracy Protects                 = on
Servo-Assisted                     = on
Acclimated                         = on
Advanced Filtration                = on
Inflammable                        = on
Electrical Conduit                 = on
Supplemental Adrenaline            = on
Med-Kit.stims                      = 4
