; Gunner: reload speed, ammo, sidearm handling, ergonomics on Med-Kit armour.
[settings]
name = Gunner

[profile: Med-Kit]
conflicts = stack
Siege-Ready                        = on
Reinforced Epaulettes              = on
Gunslinger                         = on
True Grit                          = on
Peak Physique                      = on
